import assert from "node:assert/strict";
import test from "node:test";
import { h, loadTS, renderStatic, read } from "./react-harness.mjs";
const { timingSegments, retryChain, formatFailureStage } = loadTS("web/src/logTiming.ts");
const base = { id: 3, request_uid: "same", attempt_index: 0, stream: 1, pre_upstream_ms: 20, upstream_headers_ms: 100, first_token_ms: 300, duration_ms: 1000 };
test("SSE waterfall keeps four measured stages without double-counting", () => assert.deepEqual(timingSegments(base).map((part) => part.ms), [20, 100, 200, 700]));
test("non-streamed response has preparation, headers and response-body stages", () => assert.deepEqual(timingSegments({ ...base, stream: 0 }).map((part) => part.ms), [20, 100, 900]));
test("legacy rows do not invent zero-valued timing samples", () => assert.deepEqual(timingSegments({ ...base, pre_upstream_ms: null, upstream_headers_ms: null, first_token_ms: null }).map((part) => part.ms), [null, null, null, null]));
test("retry preparation is labelled cumulative rather than charged to every attempt", () => assert.equal(timingSegments({ ...base, attempt_index: 1 })[0].label, "累计前置"));
test("invalid ordering is not rendered as a negative duration", () => assert.equal(timingSegments({ ...base, first_token_ms: 50 })[2].ms, null));
test("retry chain filters UID, de-duplicates ids and sorts attempts", () => { const next = { ...base, id: 5, attempt_index: 1 }; assert.deepEqual(retryChain(next, [next, { ...base, id: 8, request_uid: "other" }, base, base]).map((item) => item.id), [3, 5]); assert.deepEqual(retryChain({ ...base, request_uid: null }, [base]), []); });
for (const [key, value] of [["first_event", "首事件前失败"], ["stream", "传输中断"], ["client_cancelled", "客户端取消"], [null, "未记录"]]) test(`failure stage ${key} stays distinguishable`, () => assert.equal(formatFailureStage(key), value));
test("retry controls are real buttons with current state and escaped names", () => { const { RetryChain } = loadTS("web/src/components/LogTiming.tsx"); const html = renderStatic(h(RetryChain, { log: base, logs: [{ ...base, id: 4, attempt_index: 1, upstream_name: "<script>" }], onSelect() {} })); assert.match(html, /aria-pressed="true"/); assert.match(html, /&lt;script&gt;/); assert.match(html, /当前已加载/); });
test("detail metadata includes IP, request UID and failure stage together", () => { const source = read("web/src/components/LogDetailDialog.tsx"); for (const field of ["client_ip", "request_uid", "failure_stage", "failure_retryable"]) assert.ok(source.includes(field)); });
