import assert from "node:assert/strict";
import test from "node:test";
import { loadTS, read } from "./react-harness.mjs";
const { animatePresence } = loadTS("web/src/motion.ts");
function element() { const runs = []; return { runs, animate(frames, options) { let finish; const item = { frames, options, finished: new Promise((resolve) => { finish = resolve; }), cancel() { this.cancelled = true; }, finish: () => finish() }; runs.push(item); return item; } }; }
test("reduced motion and missing WAAPI fall back immediately", () => { let calls = 0; globalThis.matchMedia = () => ({ matches: true }); const node = element(); animatePresence(node, true, () => calls++); assert.equal(node.runs.length, 0); assert.equal(calls, 1); globalThis.matchMedia = () => ({ matches: false }); animatePresence({}, false, () => calls++); assert.equal(calls, 2); });
test("a superseded hide never closes a surface that was reopened", async () => { globalThis.matchMedia = () => ({ matches: false }); const node = element(); let hidden = false; animatePresence(node, false, () => { hidden = true; }); animatePresence(node, true); node.runs[0].finish(); await Promise.resolve(); assert.equal(hidden, false); assert.equal(node.runs[0].cancelled, true); node.runs[1].finish(); await Promise.resolve(); });
test("unmount cleanup cancels animation and its completion side effects", async () => { const node = element(); let settled = false; const cancel = animatePresence(node, false, () => { settled = true; }); cancel(); node.runs[0].finish(); await Promise.resolve(); assert.equal(settled, false); assert.equal(node.runs[0].cancelled, true); });
test("dialogs remain modal and inert during exit, with shared lifecycle cleanup", () => { const source = read("web/src/useDialog.ts"); assert.match(source, /dialog.showModal\(\)/); assert.match(source, /dialog.inert = !open/); assert.match(source, /return animatePresence/); assert.match(source, /pointercancel/); });
